apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-user
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend-user
  template:
    metadata:
      labels:
        app: backend-user
    spec:
      containers:
        - name: backend-user
          image: myonyein11/udagram-api-user:v4
          imagePullPolicy: Always
          envFrom:
            - configMapRef:
                name: app-config
            - secretRef:
                name: app-secret
            - secretRef:
                name: aws-secret
          ports:
            - containerPort: 8080
          resources:
            limits:
              cpu: "500m"
